version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.0
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Composer build"
      - npm install -g serverless
      - cp -r config/.env.example .env
      - composer install --ignore-platform-reqs --optimize-autoloader --no-dev
      - php artisan l5-swagger:generate
      - php artisan cache:clear
      - php artisan config:cache
      - php artisan view:clear
      - php artisan route:clear
      - serverless deploy

  post_build:
    commands:
      - echo "Updating lambda Function..."
      - echo "Dependancies Installed"
      - echo "DONE!!"
